#!/bin/sh

[ ! -e /dev/null    ] && mknod /dev/null    c 1 3
[ ! -e /dev/zero    ] && mknod /dev/zero    c 1 5
[ ! -e /dev/random  ] && mknod /dev/random  c 1 8
[ ! -e /dev/urandom ] && mknod /dev/urandom c 1 9

